=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ClientsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClientsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ClientsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClientsApi' do
    it 'should create an instance of ClientsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ClientsApi)
    end
  end

  # unit tests for clients_add_client
  # Agregar Cliente
  # 
  # @param new_client 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'clients_add_client test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for clients_delete_by_id
  # Borrar Cliente
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'clients_delete_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for clients_edit_client
  # Editar Cliente
  # 
  # @param client 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'clients_edit_client test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for clients_get
  # Obtiene la lista de clientes.
  # El filtro es opcional
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter Filters the results, based on a Boolean condition.
  # @option opts [String] :orderby Sorts the results.
  # @option opts [Integer] :top Returns only the first n results.
  # @option opts [Integer] :skip Skips the first n results.
  # @return [ClientListItemPage]
  describe 'clients_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for clients_get_details
  # Obtiene los detalles de un cliente.
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ClientDetails]
  describe 'clients_get_details test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
