=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InventoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InventoryApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InventoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InventoryApi' do
    it 'should create an instance of InventoryApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InventoryApi)
    end
  end

  # unit tests for inventory_add_inventory_adjustment
  # Agregar ajuste de inventario.
  # 
  # @param new_adjustment 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'inventory_add_inventory_adjustment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for inventory_get_inventory_by_warehouse_id
  # Obtener inventario por almacén.
  # 
  # @param warehouse_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter Filters the results, based on a Boolean condition.
  # @option opts [String] :orderby Sorts the results.
  # @option opts [Integer] :top Returns only the first n results.
  # @option opts [Integer] :skip Skips the first n results.
  # @return [InventorytPage]
  describe 'inventory_get_inventory_by_warehouse_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
