=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InvoicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InvoicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InvoicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoicesApi' do
    it 'should create an instance of InvoicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InvoicesApi)
    end
  end

  # unit tests for invoices_add_invoice
  # Agregar factura
  # 
  # @param new_invoice 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'invoices_add_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_add_payment
  # Registrar pago a factura
  # 
  # @param new_payment 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoices_add_payment test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_delete_invoice
  # Eliminar factura
  # 
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoices_delete_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_get_by_id
  # Obtiene los detalles de una venta
  # 
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [InvoiceDetails]
  describe 'invoices_get_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_get_by_number
  # Obtiene los detalles de una venta
  # 
  # @param number Serie y Número
  # @param [Hash] opts the optional parameters
  # @return [InvoiceDetails]
  describe 'invoices_get_by_number test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_get_pdf
  # Obtener el PDF de una venta
  # 
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'invoices_get_pdf test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoices_get_xml
  # Obtener el XML de una venta
  # 
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'invoices_get_xml test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
