=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::OrdersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@instance).to be_instance_of(SwaggerClient::OrdersApi)
    end
  end

  # unit tests for orders_add_order
  # Agregar pedido
  # 
  # @param new_order 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'orders_add_order test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_delete_order
  # Eliminar pedido
  # 
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'orders_delete_order test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_edit_order
  # Editar pedido
  # 
  # @param order 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'orders_edit_order test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_get_by_id
  # Obtiene los detalles de un pedido
  # 
  # @param id ID
  # @param [Hash] opts the optional parameters
  # @return [OrderDetails]
  describe 'orders_get_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
