=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ProvidersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProvidersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ProvidersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProvidersApi' do
    it 'should create an instance of ProvidersApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ProvidersApi)
    end
  end

  # unit tests for providers_add_provider
  # Agregar Proveedor
  # 
  # @param new_provider 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'providers_add_provider test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for providers_delete_by_id
  # Borrar Proveedor
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'providers_delete_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for providers_edit_provider
  # Editar Proveedor
  # 
  # @param provider 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'providers_edit_provider test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for providers_get_providers
  # Obtiene la lista de proveedores.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter Filters the results, based on a Boolean condition.
  # @option opts [String] :orderby Sorts the results.
  # @option opts [Integer] :top Returns only the first n results.
  # @option opts [Integer] :skip Skips the first n results.
  # @return [ProviderListItemPage]
  describe 'providers_get_providers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
