=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServicesApi' do
    it 'should create an instance of ServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ServicesApi)
    end
  end

  # unit tests for services_add_product
  # Agregar Concepto de Venta
  # 
  # @param new_service 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'services_add_product test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_delete_by_id
  # Borrar Servicio
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'services_delete_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_edit_product
  # Editar Concepto de Venta
  # 
  # @param service 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'services_edit_product test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for services_get_services
  # Obtiene la lista de conceptos de venta.
  # El filtro es opcional
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter Filters the results, based on a Boolean condition.
  # @option opts [String] :orderby Sorts the results.
  # @option opts [Integer] :top Returns only the first n results.
  # @option opts [Integer] :skip Skips the first n results.
  # @return [ServicesPage]
  describe 'services_get_services test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
