=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::WebHooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebHooksApi' do
  before do
    # run before each test
    @instance = SwaggerClient::WebHooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebHooksApi' do
    it 'should create an instance of WebHooksApi' do
      expect(@instance).to be_instance_of(SwaggerClient::WebHooksApi)
    end
  end

  # unit tests for web_hooks_add_web_hook_subscriptions
  # Suscribirse a un WebHook
  # 
  # @param web_hook_subscription 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'web_hooks_add_web_hook_subscriptions test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for web_hooks_delete_web_hook_subscriptio_by_id
  # Borrar suscripción a WebHook
  # 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'web_hooks_delete_web_hook_subscriptio_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for web_hooks_edit_web_hook_subscription
  # Editar suscripción a WebHook
  # 
  # @param web_hook_subscription 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'web_hooks_edit_web_hook_subscription test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for web_hooks_get_web_hook_sample_data
  # Obtiene un ejemplo del modelo de datos que envía el WebHook.
  # 
  # @param event_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'web_hooks_get_web_hook_sample_data test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for web_hooks_get_web_hook_subscriptions
  # Obtiene la lista de su suscripciones a WebHooks
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter Filters the results, based on a Boolean condition.
  # @option opts [String] :orderby Sorts the results.
  # @option opts [Integer] :top Returns only the first n results.
  # @option opts [Integer] :skip Skips the first n results.
  # @return [WebHookSubscriptionPage]
  describe 'web_hooks_get_web_hook_subscriptions test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for web_hooks_get_web_hooks
  # Obtiene la lista de WebHooks disponibles.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter Filters the results, based on a Boolean condition.
  # @option opts [String] :orderby Sorts the results.
  # @option opts [Integer] :top Returns only the first n results.
  # @option opts [Integer] :skip Skips the first n results.
  # @return [WebHookPage]
  describe 'web_hooks_get_web_hooks test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
