=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::OrderDetails
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OrderDetails' do
  before do
    # run before each test
    @instance = SwaggerClient::OrderDetails.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderDetails' do
    it 'should create an instance of OrderDetails' do
      expect(@instance).to be_instance_of(SwaggerClient::OrderDetails)
    end
  end
end

