=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ProductPrices
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductPrices' do
  before do
    # run before each test
    @instance = SwaggerClient::ProductPrices.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductPrices' do
    it 'should create an instance of ProductPrices' do
      expect(@instance).to be_instance_of(SwaggerClient::ProductPrices)
    end
  end
  describe 'test attribute "items"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

