=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module SwaggerClient

  class InvoiceDetails
    attr_accessor :id

    attr_accessor :series

    attr_accessor :number

    attr_accessor :client_id

    attr_accessor :client_name

    attr_accessor :payment_terms

    attr_accessor :status

    attr_accessor :status_code

    attr_accessor :client_phone_number

    attr_accessor :client_contact

    attr_accessor :rfc

    attr_accessor :created_by_id

    attr_accessor :created_by_name

    attr_accessor :creation_date

    attr_accessor :application_date

    attr_accessor :price_list_id

    attr_accessor :price_list_name

    attr_accessor :location_id

    attr_accessor :location_name

    attr_accessor :warehouse_id

    attr_accessor :warehouse_name

    attr_accessor :cfdi_payment_method

    attr_accessor :cfdi_payment_term

    attr_accessor :cfdi_account_number

    attr_accessor :currency_name

    attr_accessor :exchange_rate

    attr_accessor :purchase_order

    attr_accessor :fiscal_id

    attr_accessor :address

    attr_accessor :comments

    attr_accessor :subtotal

    attr_accessor :discount

    attr_accessor :vat

    attr_accessor :ieps

    attr_accessor :vat_ret

    attr_accessor :isr_ret

    attr_accessor :payments

    attr_accessor :credit_notes

    attr_accessor :products

    attr_accessor :services


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'ID',
        :'series' => :'Series',
        :'number' => :'Number',
        :'client_id' => :'ClientID',
        :'client_name' => :'ClientName',
        :'payment_terms' => :'PaymentTerms',
        :'status' => :'Status',
        :'status_code' => :'StatusCode',
        :'client_phone_number' => :'ClientPhoneNumber',
        :'client_contact' => :'ClientContact',
        :'rfc' => :'RFC',
        :'created_by_id' => :'CreatedByID',
        :'created_by_name' => :'CreatedByName',
        :'creation_date' => :'CreationDate',
        :'application_date' => :'ApplicationDate',
        :'price_list_id' => :'PriceListID',
        :'price_list_name' => :'PriceListName',
        :'location_id' => :'LocationID',
        :'location_name' => :'LocationName',
        :'warehouse_id' => :'WarehouseID',
        :'warehouse_name' => :'WarehouseName',
        :'cfdi_payment_method' => :'CFDIPaymentMethod',
        :'cfdi_payment_term' => :'CFDIPaymentTerm',
        :'cfdi_account_number' => :'CFDIAccountNumber',
        :'currency_name' => :'CurrencyName',
        :'exchange_rate' => :'ExchangeRate',
        :'purchase_order' => :'PurchaseOrder',
        :'fiscal_id' => :'FiscalID',
        :'address' => :'Address',
        :'comments' => :'Comments',
        :'subtotal' => :'Subtotal',
        :'discount' => :'Discount',
        :'vat' => :'VAT',
        :'ieps' => :'IEPS',
        :'vat_ret' => :'VATRet',
        :'isr_ret' => :'ISRRet',
        :'payments' => :'Payments',
        :'credit_notes' => :'CreditNotes',
        :'products' => :'Products',
        :'services' => :'Services'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'series' => :'String',
        :'number' => :'Integer',
        :'client_id' => :'String',
        :'client_name' => :'String',
        :'payment_terms' => :'Integer',
        :'status' => :'String',
        :'status_code' => :'Integer',
        :'client_phone_number' => :'String',
        :'client_contact' => :'String',
        :'rfc' => :'String',
        :'created_by_id' => :'String',
        :'created_by_name' => :'String',
        :'creation_date' => :'DateTime',
        :'application_date' => :'DateTime',
        :'price_list_id' => :'String',
        :'price_list_name' => :'String',
        :'location_id' => :'String',
        :'location_name' => :'String',
        :'warehouse_id' => :'String',
        :'warehouse_name' => :'String',
        :'cfdi_payment_method' => :'String',
        :'cfdi_payment_term' => :'String',
        :'cfdi_account_number' => :'String',
        :'currency_name' => :'String',
        :'exchange_rate' => :'Float',
        :'purchase_order' => :'String',
        :'fiscal_id' => :'String',
        :'address' => :'String',
        :'comments' => :'String',
        :'subtotal' => :'Float',
        :'discount' => :'Float',
        :'vat' => :'Float',
        :'ieps' => :'Float',
        :'vat_ret' => :'Float',
        :'isr_ret' => :'Float',
        :'payments' => :'Float',
        :'credit_notes' => :'Float',
        :'products' => :'Array<InvoiceDetailsProduct>',
        :'services' => :'Array<InvoiceDetailsService>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'ID')
        self.id = attributes[:'ID']
      end

      if attributes.has_key?(:'Series')
        self.series = attributes[:'Series']
      end

      if attributes.has_key?(:'Number')
        self.number = attributes[:'Number']
      end

      if attributes.has_key?(:'ClientID')
        self.client_id = attributes[:'ClientID']
      end

      if attributes.has_key?(:'ClientName')
        self.client_name = attributes[:'ClientName']
      end

      if attributes.has_key?(:'PaymentTerms')
        self.payment_terms = attributes[:'PaymentTerms']
      end

      if attributes.has_key?(:'Status')
        self.status = attributes[:'Status']
      end

      if attributes.has_key?(:'StatusCode')
        self.status_code = attributes[:'StatusCode']
      end

      if attributes.has_key?(:'ClientPhoneNumber')
        self.client_phone_number = attributes[:'ClientPhoneNumber']
      end

      if attributes.has_key?(:'ClientContact')
        self.client_contact = attributes[:'ClientContact']
      end

      if attributes.has_key?(:'RFC')
        self.rfc = attributes[:'RFC']
      end

      if attributes.has_key?(:'CreatedByID')
        self.created_by_id = attributes[:'CreatedByID']
      end

      if attributes.has_key?(:'CreatedByName')
        self.created_by_name = attributes[:'CreatedByName']
      end

      if attributes.has_key?(:'CreationDate')
        self.creation_date = attributes[:'CreationDate']
      end

      if attributes.has_key?(:'ApplicationDate')
        self.application_date = attributes[:'ApplicationDate']
      end

      if attributes.has_key?(:'PriceListID')
        self.price_list_id = attributes[:'PriceListID']
      end

      if attributes.has_key?(:'PriceListName')
        self.price_list_name = attributes[:'PriceListName']
      end

      if attributes.has_key?(:'LocationID')
        self.location_id = attributes[:'LocationID']
      end

      if attributes.has_key?(:'LocationName')
        self.location_name = attributes[:'LocationName']
      end

      if attributes.has_key?(:'WarehouseID')
        self.warehouse_id = attributes[:'WarehouseID']
      end

      if attributes.has_key?(:'WarehouseName')
        self.warehouse_name = attributes[:'WarehouseName']
      end

      if attributes.has_key?(:'CFDIPaymentMethod')
        self.cfdi_payment_method = attributes[:'CFDIPaymentMethod']
      end

      if attributes.has_key?(:'CFDIPaymentTerm')
        self.cfdi_payment_term = attributes[:'CFDIPaymentTerm']
      end

      if attributes.has_key?(:'CFDIAccountNumber')
        self.cfdi_account_number = attributes[:'CFDIAccountNumber']
      end

      if attributes.has_key?(:'CurrencyName')
        self.currency_name = attributes[:'CurrencyName']
      end

      if attributes.has_key?(:'ExchangeRate')
        self.exchange_rate = attributes[:'ExchangeRate']
      end

      if attributes.has_key?(:'PurchaseOrder')
        self.purchase_order = attributes[:'PurchaseOrder']
      end

      if attributes.has_key?(:'FiscalID')
        self.fiscal_id = attributes[:'FiscalID']
      end

      if attributes.has_key?(:'Address')
        self.address = attributes[:'Address']
      end

      if attributes.has_key?(:'Comments')
        self.comments = attributes[:'Comments']
      end

      if attributes.has_key?(:'Subtotal')
        self.subtotal = attributes[:'Subtotal']
      end

      if attributes.has_key?(:'Discount')
        self.discount = attributes[:'Discount']
      end

      if attributes.has_key?(:'VAT')
        self.vat = attributes[:'VAT']
      end

      if attributes.has_key?(:'IEPS')
        self.ieps = attributes[:'IEPS']
      end

      if attributes.has_key?(:'VATRet')
        self.vat_ret = attributes[:'VATRet']
      end

      if attributes.has_key?(:'ISRRet')
        self.isr_ret = attributes[:'ISRRet']
      end

      if attributes.has_key?(:'Payments')
        self.payments = attributes[:'Payments']
      end

      if attributes.has_key?(:'CreditNotes')
        self.credit_notes = attributes[:'CreditNotes']
      end

      if attributes.has_key?(:'Products')
        if (value = attributes[:'Products']).is_a?(Array)
          self.products = value
        end
      end

      if attributes.has_key?(:'Services')
        if (value = attributes[:'Services']).is_a?(Array)
          self.services = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          series == o.series &&
          number == o.number &&
          client_id == o.client_id &&
          client_name == o.client_name &&
          payment_terms == o.payment_terms &&
          status == o.status &&
          status_code == o.status_code &&
          client_phone_number == o.client_phone_number &&
          client_contact == o.client_contact &&
          rfc == o.rfc &&
          created_by_id == o.created_by_id &&
          created_by_name == o.created_by_name &&
          creation_date == o.creation_date &&
          application_date == o.application_date &&
          price_list_id == o.price_list_id &&
          price_list_name == o.price_list_name &&
          location_id == o.location_id &&
          location_name == o.location_name &&
          warehouse_id == o.warehouse_id &&
          warehouse_name == o.warehouse_name &&
          cfdi_payment_method == o.cfdi_payment_method &&
          cfdi_payment_term == o.cfdi_payment_term &&
          cfdi_account_number == o.cfdi_account_number &&
          currency_name == o.currency_name &&
          exchange_rate == o.exchange_rate &&
          purchase_order == o.purchase_order &&
          fiscal_id == o.fiscal_id &&
          address == o.address &&
          comments == o.comments &&
          subtotal == o.subtotal &&
          discount == o.discount &&
          vat == o.vat &&
          ieps == o.ieps &&
          vat_ret == o.vat_ret &&
          isr_ret == o.isr_ret &&
          payments == o.payments &&
          credit_notes == o.credit_notes &&
          products == o.products &&
          services == o.services
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, series, number, client_id, client_name, payment_terms, status, status_code, client_phone_number, client_contact, rfc, created_by_id, created_by_name, creation_date, application_date, price_list_id, price_list_name, location_id, location_name, warehouse_id, warehouse_name, cfdi_payment_method, cfdi_payment_term, cfdi_account_number, currency_name, exchange_rate, purchase_order, fiscal_id, address, comments, subtotal, discount, vat, ieps, vat_ret, isr_ret, payments, credit_notes, products, services].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
