=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module SwaggerClient

  class NewService
    attr_accessor :code

    attr_accessor :title

    attr_accessor :currency_id

    attr_accessor :sat_company_account_id

    attr_accessor :measurement_unit

    attr_accessor :description

    attr_accessor :category1_id

    attr_accessor :category2_id

    attr_accessor :category3_id

    attr_accessor :variable_concept

    attr_accessor :charge_vat


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'code' => :'Code',
        :'title' => :'Title',
        :'currency_id' => :'CurrencyID',
        :'sat_company_account_id' => :'SATCompanyAccountID',
        :'measurement_unit' => :'MeasurementUnit',
        :'description' => :'Description',
        :'category1_id' => :'Category1ID',
        :'category2_id' => :'Category2ID',
        :'category3_id' => :'Category3ID',
        :'variable_concept' => :'VariableConcept',
        :'charge_vat' => :'ChargeVAT'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'code' => :'String',
        :'title' => :'String',
        :'currency_id' => :'String',
        :'sat_company_account_id' => :'String',
        :'measurement_unit' => :'String',
        :'description' => :'String',
        :'category1_id' => :'String',
        :'category2_id' => :'String',
        :'category3_id' => :'String',
        :'variable_concept' => :'BOOLEAN',
        :'charge_vat' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'Code')
        self.code = attributes[:'Code']
      end

      if attributes.has_key?(:'Title')
        self.title = attributes[:'Title']
      end

      if attributes.has_key?(:'CurrencyID')
        self.currency_id = attributes[:'CurrencyID']
      end

      if attributes.has_key?(:'SATCompanyAccountID')
        self.sat_company_account_id = attributes[:'SATCompanyAccountID']
      end

      if attributes.has_key?(:'MeasurementUnit')
        self.measurement_unit = attributes[:'MeasurementUnit']
      end

      if attributes.has_key?(:'Description')
        self.description = attributes[:'Description']
      end

      if attributes.has_key?(:'Category1ID')
        self.category1_id = attributes[:'Category1ID']
      end

      if attributes.has_key?(:'Category2ID')
        self.category2_id = attributes[:'Category2ID']
      end

      if attributes.has_key?(:'Category3ID')
        self.category3_id = attributes[:'Category3ID']
      end

      if attributes.has_key?(:'VariableConcept')
        self.variable_concept = attributes[:'VariableConcept']
      end

      if attributes.has_key?(:'ChargeVAT')
        self.charge_vat = attributes[:'ChargeVAT']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @code.nil?
        invalid_properties.push("invalid value for 'code', code cannot be nil.")
      end

      if @title.nil?
        invalid_properties.push("invalid value for 'title', title cannot be nil.")
      end

      if @currency_id.nil?
        invalid_properties.push("invalid value for 'currency_id', currency_id cannot be nil.")
      end

      if @sat_company_account_id.nil?
        invalid_properties.push("invalid value for 'sat_company_account_id', sat_company_account_id cannot be nil.")
      end

      if @measurement_unit.nil?
        invalid_properties.push("invalid value for 'measurement_unit', measurement_unit cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @code.nil?
      return false if @title.nil?
      return false if @currency_id.nil?
      return false if @sat_company_account_id.nil?
      return false if @measurement_unit.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          code == o.code &&
          title == o.title &&
          currency_id == o.currency_id &&
          sat_company_account_id == o.sat_company_account_id &&
          measurement_unit == o.measurement_unit &&
          description == o.description &&
          category1_id == o.category1_id &&
          category2_id == o.category2_id &&
          category3_id == o.category3_id &&
          variable_concept == o.variable_concept &&
          charge_vat == o.charge_vat
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [code, title, currency_id, sat_company_account_id, measurement_unit, description, category1_id, category2_id, category3_id, variable_concept, charge_vat].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
