=begin
#Bind ERP API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'date'

module SwaggerClient

  class OrderDetails
    attr_accessor :id

    attr_accessor :client_id

    attr_accessor :client_name

    attr_accessor :price_list_name

    attr_accessor :price_list_id

    attr_accessor :location_name

    attr_accessor :location_id

    attr_accessor :warehouse_id

    attr_accessor :warehouse_name

    attr_accessor :order_date

    attr_accessor :comments

    attr_accessor :number

    attr_accessor :address

    attr_accessor :client_contact

    attr_accessor :phone_number

    attr_accessor :employee_name

    attr_accessor :employee_id

    attr_accessor :status_code

    attr_accessor :purchase_order

    attr_accessor :status

    attr_accessor :currency_name

    attr_accessor :currency_id

    attr_accessor :exchange_rate

    attr_accessor :rfc

    attr_accessor :service_subtotal

    attr_accessor :product_subtotal

    attr_accessor :discount

    attr_accessor :vat_rate

    attr_accessor :vat

    attr_accessor :discount_type

    attr_accessor :ieps

    attr_accessor :iepsrate

    attr_accessor :isr_ret

    attr_accessor :isr_ret_rate

    attr_accessor :vat_ret

    attr_accessor :vat_ret_rate

    attr_accessor :total

    attr_accessor :products

    attr_accessor :services


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'ID',
        :'client_id' => :'ClientID',
        :'client_name' => :'ClientName',
        :'price_list_name' => :'PriceListName',
        :'price_list_id' => :'PriceListID',
        :'location_name' => :'LocationName',
        :'location_id' => :'LocationID',
        :'warehouse_id' => :'WarehouseID',
        :'warehouse_name' => :'WarehouseName',
        :'order_date' => :'OrderDate',
        :'comments' => :'Comments',
        :'number' => :'Number',
        :'address' => :'Address',
        :'client_contact' => :'ClientContact',
        :'phone_number' => :'PhoneNumber',
        :'employee_name' => :'EmployeeName',
        :'employee_id' => :'EmployeeID',
        :'status_code' => :'StatusCode',
        :'purchase_order' => :'PurchaseOrder',
        :'status' => :'Status',
        :'currency_name' => :'CurrencyName',
        :'currency_id' => :'CurrencyID',
        :'exchange_rate' => :'ExchangeRate',
        :'rfc' => :'RFC',
        :'service_subtotal' => :'ServiceSubtotal',
        :'product_subtotal' => :'ProductSubtotal',
        :'discount' => :'Discount',
        :'vat_rate' => :'VATRate',
        :'vat' => :'VAT',
        :'discount_type' => :'DiscountType',
        :'ieps' => :'IEPS',
        :'iepsrate' => :'IEPSRATE',
        :'isr_ret' => :'ISRRet',
        :'isr_ret_rate' => :'ISRRetRate',
        :'vat_ret' => :'VatRet',
        :'vat_ret_rate' => :'VatRetRate',
        :'total' => :'Total',
        :'products' => :'Products',
        :'services' => :'Services'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'client_id' => :'String',
        :'client_name' => :'String',
        :'price_list_name' => :'String',
        :'price_list_id' => :'String',
        :'location_name' => :'String',
        :'location_id' => :'String',
        :'warehouse_id' => :'String',
        :'warehouse_name' => :'String',
        :'order_date' => :'DateTime',
        :'comments' => :'String',
        :'number' => :'Integer',
        :'address' => :'String',
        :'client_contact' => :'String',
        :'phone_number' => :'String',
        :'employee_name' => :'String',
        :'employee_id' => :'String',
        :'status_code' => :'Integer',
        :'purchase_order' => :'String',
        :'status' => :'String',
        :'currency_name' => :'String',
        :'currency_id' => :'String',
        :'exchange_rate' => :'Float',
        :'rfc' => :'String',
        :'service_subtotal' => :'Float',
        :'product_subtotal' => :'Float',
        :'discount' => :'Float',
        :'vat_rate' => :'Float',
        :'vat' => :'Float',
        :'discount_type' => :'Integer',
        :'ieps' => :'Float',
        :'iepsrate' => :'Float',
        :'isr_ret' => :'Float',
        :'isr_ret_rate' => :'Float',
        :'vat_ret' => :'Float',
        :'vat_ret_rate' => :'Float',
        :'total' => :'Float',
        :'products' => :'Array<OrderDetailsProduct>',
        :'services' => :'Array<OrderDetailsService>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'ID')
        self.id = attributes[:'ID']
      end

      if attributes.has_key?(:'ClientID')
        self.client_id = attributes[:'ClientID']
      end

      if attributes.has_key?(:'ClientName')
        self.client_name = attributes[:'ClientName']
      end

      if attributes.has_key?(:'PriceListName')
        self.price_list_name = attributes[:'PriceListName']
      end

      if attributes.has_key?(:'PriceListID')
        self.price_list_id = attributes[:'PriceListID']
      end

      if attributes.has_key?(:'LocationName')
        self.location_name = attributes[:'LocationName']
      end

      if attributes.has_key?(:'LocationID')
        self.location_id = attributes[:'LocationID']
      end

      if attributes.has_key?(:'WarehouseID')
        self.warehouse_id = attributes[:'WarehouseID']
      end

      if attributes.has_key?(:'WarehouseName')
        self.warehouse_name = attributes[:'WarehouseName']
      end

      if attributes.has_key?(:'OrderDate')
        self.order_date = attributes[:'OrderDate']
      end

      if attributes.has_key?(:'Comments')
        self.comments = attributes[:'Comments']
      end

      if attributes.has_key?(:'Number')
        self.number = attributes[:'Number']
      end

      if attributes.has_key?(:'Address')
        self.address = attributes[:'Address']
      end

      if attributes.has_key?(:'ClientContact')
        self.client_contact = attributes[:'ClientContact']
      end

      if attributes.has_key?(:'PhoneNumber')
        self.phone_number = attributes[:'PhoneNumber']
      end

      if attributes.has_key?(:'EmployeeName')
        self.employee_name = attributes[:'EmployeeName']
      end

      if attributes.has_key?(:'EmployeeID')
        self.employee_id = attributes[:'EmployeeID']
      end

      if attributes.has_key?(:'StatusCode')
        self.status_code = attributes[:'StatusCode']
      end

      if attributes.has_key?(:'PurchaseOrder')
        self.purchase_order = attributes[:'PurchaseOrder']
      end

      if attributes.has_key?(:'Status')
        self.status = attributes[:'Status']
      end

      if attributes.has_key?(:'CurrencyName')
        self.currency_name = attributes[:'CurrencyName']
      end

      if attributes.has_key?(:'CurrencyID')
        self.currency_id = attributes[:'CurrencyID']
      end

      if attributes.has_key?(:'ExchangeRate')
        self.exchange_rate = attributes[:'ExchangeRate']
      end

      if attributes.has_key?(:'RFC')
        self.rfc = attributes[:'RFC']
      end

      if attributes.has_key?(:'ServiceSubtotal')
        self.service_subtotal = attributes[:'ServiceSubtotal']
      end

      if attributes.has_key?(:'ProductSubtotal')
        self.product_subtotal = attributes[:'ProductSubtotal']
      end

      if attributes.has_key?(:'Discount')
        self.discount = attributes[:'Discount']
      end

      if attributes.has_key?(:'VATRate')
        self.vat_rate = attributes[:'VATRate']
      end

      if attributes.has_key?(:'VAT')
        self.vat = attributes[:'VAT']
      end

      if attributes.has_key?(:'DiscountType')
        self.discount_type = attributes[:'DiscountType']
      end

      if attributes.has_key?(:'IEPS')
        self.ieps = attributes[:'IEPS']
      end

      if attributes.has_key?(:'IEPSRATE')
        self.iepsrate = attributes[:'IEPSRATE']
      end

      if attributes.has_key?(:'ISRRet')
        self.isr_ret = attributes[:'ISRRet']
      end

      if attributes.has_key?(:'ISRRetRate')
        self.isr_ret_rate = attributes[:'ISRRetRate']
      end

      if attributes.has_key?(:'VatRet')
        self.vat_ret = attributes[:'VatRet']
      end

      if attributes.has_key?(:'VatRetRate')
        self.vat_ret_rate = attributes[:'VatRetRate']
      end

      if attributes.has_key?(:'Total')
        self.total = attributes[:'Total']
      end

      if attributes.has_key?(:'Products')
        if (value = attributes[:'Products']).is_a?(Array)
          self.products = value
        end
      end

      if attributes.has_key?(:'Services')
        if (value = attributes[:'Services']).is_a?(Array)
          self.services = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          client_id == o.client_id &&
          client_name == o.client_name &&
          price_list_name == o.price_list_name &&
          price_list_id == o.price_list_id &&
          location_name == o.location_name &&
          location_id == o.location_id &&
          warehouse_id == o.warehouse_id &&
          warehouse_name == o.warehouse_name &&
          order_date == o.order_date &&
          comments == o.comments &&
          number == o.number &&
          address == o.address &&
          client_contact == o.client_contact &&
          phone_number == o.phone_number &&
          employee_name == o.employee_name &&
          employee_id == o.employee_id &&
          status_code == o.status_code &&
          purchase_order == o.purchase_order &&
          status == o.status &&
          currency_name == o.currency_name &&
          currency_id == o.currency_id &&
          exchange_rate == o.exchange_rate &&
          rfc == o.rfc &&
          service_subtotal == o.service_subtotal &&
          product_subtotal == o.product_subtotal &&
          discount == o.discount &&
          vat_rate == o.vat_rate &&
          vat == o.vat &&
          discount_type == o.discount_type &&
          ieps == o.ieps &&
          iepsrate == o.iepsrate &&
          isr_ret == o.isr_ret &&
          isr_ret_rate == o.isr_ret_rate &&
          vat_ret == o.vat_ret &&
          vat_ret_rate == o.vat_ret_rate &&
          total == o.total &&
          products == o.products &&
          services == o.services
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, client_id, client_name, price_list_name, price_list_id, location_name, location_id, warehouse_id, warehouse_name, order_date, comments, number, address, client_contact, phone_number, employee_name, employee_id, status_code, purchase_order, status, currency_name, currency_id, exchange_rate, rfc, service_subtotal, product_subtotal, discount, vat_rate, vat, discount_type, ieps, iepsrate, isr_ret, isr_ret_rate, vat_ret, vat_ret_rate, total, products, services].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
